global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: muscle-boost-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - mb-prod-app-1:3000
        labels:
          compose_project: mb-prod
      - targets:
          - mb-staging-app-1:3001
        labels:
          compose_project: mb-staging
