export const SESSION_LAST_ONLINE_THRESHOLD_MINUTES_KEY =
  'SESSION_LAST_ONLINE_THRESHOLD_MINUTES' as const;
export const REFRESH_ROTATION_GRACE_SECONDS_KEY =
  'REFRESH_ROTATION_GRACE_SECONDS' as const;
